/**
 * The composed-document boundary: sections in, one document out.
 *
 * `spine.ts` decides WHAT a coworker's document says — types, overlays,
 * workflows, traits. This module decides how a list of sections becomes a
 * document: heading levels, separators, the composer marker, and which sections
 * may be evicted when the result would exceed the consumer's size cap.
 *
 * Why a role discriminator rather than a `droppable` flag plus a name:
 * assembly asks three questions that a flag cannot answer — where does the size
 * notice go (before the persona), is this heading still meaningful (a group
 * header whose members were all evicted), and which H1 is the document title.
 * Name-matching for those made the earlier design admit droppable titles,
 * multiple personas, and grouped notices. Here they are unrepresentable.
 *
 * The cap ladder lives here for the reason `doc-size-cap.ts:39` records: eviction
 * was deferred "until the fork wires droppable sections that can actually absorb
 * the overflow", and per-server MCP sections are that source.
 */
import crypto from 'crypto';

import { PROJECT_DOC_MAX_BYTES, ProjectDocTooLargeError } from './doc-size-cap.js';

/** Byte cost of the `\n\n` a non-final section contributes to the join. */
const SEPARATOR_BYTES = 2;

interface Base {
  readonly name: string;
  readonly body: string;
  readonly heading: { readonly kind: 'titled'; readonly level: 1 | 2 } | { readonly kind: 'verbatim' };
}

/**
 * What a PRODUCER may hand the composer. `notice` is absent by construction:
 * the size notice is generated by the ladder, and a caller-supplied one could
 * claim an eviction that never happened.
 */
export type ComposedSectionInput =
  | (Base & { readonly role: 'title'; readonly droppable: false })
  | (Base & { readonly role: 'persona'; readonly droppable: false })
  | (Base & { readonly role: 'body'; readonly droppable: boolean; readonly group?: string })
  | (Base & { readonly role: 'group-header'; readonly droppable: false; readonly group: string });

type ComposedSection = ComposedSectionInput | (Base & { readonly role: 'notice'; readonly droppable: false });

export interface ProjectDocSpec {
  readonly fileName: string;
  /** Undefined ⇒ no cap and no ladder. Set for every real caller. */
  readonly maxBytes?: number;
  /**
   * REQUIRED and non-empty. This spec carries no other content source, so an
   * empty list would publish a marker-only document — which
   * `assertComposedDocUsable` accepts as usable (it checks `trim().length > 0`),
   * letting a group spawn with no instructions at all, silently.
   */
  readonly extraSections: readonly [ComposedSectionInput, ...ComposedSectionInput[]];
}

export interface CapDiagnostics {
  readonly bytes: number;
  /**
   * Absent ⇔ no cap was configured. A required `number` cannot express that, and
   * every stand-in lies: `0` reads as "cap of zero, everything overflows",
   * `Infinity` serializes to `null` through the JSON logger, and
   * `PROJECT_DOC_MAX_BYTES` claims a cap that was never applied.
   */
  readonly maxBytes?: number;
  /** Rendered-block bytes per surviving section: heading + body + separator. */
  readonly sections: readonly { readonly name: string; readonly bytes: number }[];
  /** Necessarily false when `maxBytes` is absent — nothing to be near. */
  readonly nearCap: boolean;
  /**
   * Group headers dropped because the ladder evicted their last member. NOT
   * headers that were never built: a wrapper for zero configured servers is
   * absent, not omitted, and reporting it would log a phantom "omitted for size"
   * on every spawn of every group that wires no MCP servers.
   */
  readonly structurallyOmitted: readonly string[];
}

export interface RenderedProjectDoc {
  readonly content: string;
  readonly hash: string;
  readonly dropped: readonly string[];
  readonly diagnostics: CapDiagnostics;
}

/**
 * Both fence styles, unlike the three backtick-only scanners this replaces
 * (`spine.ts:190`/`:244`, `runtime-contract.ts:64`). A tilde-fenced block is
 * valid CommonMark, so a title check built on backticks alone would accept
 * `~~~\n# fake\n~~~` as the document's H1.
 *
 * Three CommonMark rules this has to honor, each of which flips a title verdict
 * the wrong way when dropped:
 *
 *  - A closing fence carries nothing but the fence and whitespace. `` ```not-close ``
 *    is fence CONTENT, and treating it as a closer ends the block early — so a
 *    `# heading` still inside the code block becomes the document's H1.
 *  - At most three spaces of indent open a fence; four make an indented code
 *    block. Treating `    ```{.js}` as an opener swallows the rest of the
 *    document, hiding the real H1 and failing a valid section.
 *  - An info string may not contain a backtick on a backtick fence, so
 *    `` ```a`b `` opens nothing.
 */
export function stripFencedBlocks(md: string): string[] {
  const out: string[] = [];
  let fence: { char: string; length: number } | undefined;
  for (const line of md.split('\n')) {
    const m = line.match(/^ {0,3}(`{3,}|~{3,})(.*)$/);
    if (fence) {
      if (m && m[1][0] === fence.char && m[1].length >= fence.length && /^[ \t\r]*$/.test(m[2])) {
        fence = undefined;
      }
      continue;
    }
    if (m && (m[1][0] === '~' || !m[2].includes('`'))) {
      fence = { char: m[1][0], length: m[1].length };
      continue;
    }
    out.push(line);
  }
  return out;
}

/** First ATX heading outside any fenced block, or undefined. */
function firstHeadingLevel(md: string): number | undefined {
  for (const line of stripFencedBlocks(md)) {
    const m = line.match(/^(#{1,6}) \S/);
    if (m) return m[1].length;
  }
  return undefined;
}

/**
 * Structural invariants the type cannot carry: cardinality, ordering, and group
 * topology. Every rule here has a negative test, because the parity fixtures
 * exercise only valid producers — none of these states is reachable from them,
 * so byte-parity cannot catch a missing rule.
 */
function validate(sections: readonly ComposedSectionInput[]): void {
  const titles = sections.filter((s) => s.role === 'title');
  // Both bounds, separately: a `> 1` check alone accepts a document with no H1,
  // where the persona silently becomes the title.
  if (titles.length > 1)
    throw new Error(`Composed document has ${titles.length} title sections; exactly one is required`);
  if (titles.length === 0) throw new Error('Composed document has no title section; exactly one is required');
  if (sections[0].role !== 'title') throw new Error(`Title section must come first; found '${sections[0].name}'`);

  // The title owns the document's opening H1. On the flat path the identity body
  // IS the title section and carries its own `# Title`, so a flat identity with
  // no H1 must fail rather than silently cede the heading to a later section.
  const title = titles[0];
  const titleLevel = title.heading.kind === 'titled' ? title.heading.level : firstHeadingLevel(title.body);
  if (titleLevel !== 1) {
    throw new Error(`Title section '${title.name}' must render an H1 (found ${titleLevel ?? 'no heading'})`);
  }

  const personas = sections.filter((s) => s.role === 'persona');
  if (personas.length > 1) {
    // The notice is placed "before the persona"; two makes that undefined.
    throw new Error(`Composed document has ${personas.length} persona sections; at most one is allowed`);
  }
  if (personas.length === 1 && sections[sections.length - 1].role !== 'persona') {
    // Last-word precedence (`spine.ts:919-921`): content after the persona
    // silently overrides the operator's own instructions.
    throw new Error('Persona section must be last');
  }

  for (const s of sections) {
    if (s.role !== 'title' && s.heading.kind === 'titled' && s.heading.level === 1) {
      throw new Error(`Section '${s.name}' synthesizes an H1; only the title section may`);
    }
  }

  validateGroups(sections);
}

/**
 * Group topology: a group is ONE CONTIGUOUS RUN starting at its header. The
 * ladder depends on that — it evicts members, then asks whether a header has any
 * left, which is only meaningful if the survivors are the run under that header.
 */
function validateGroups(sections: readonly ComposedSectionInput[]): void {
  const headerAt = new Map<string, number>();
  sections.forEach((s, i) => {
    if (s.role !== 'group-header') return;
    if (headerAt.has(s.group)) throw new Error(`Group '${s.group}' has more than one header`);
    headerAt.set(s.group, i);
  });

  const memberIndexes = new Map<string, number[]>();
  sections.forEach((s, i) => {
    const group = s.role === 'body' ? s.group : undefined;
    if (group === undefined) return;
    if (!headerAt.has(group)) throw new Error(`Section '${s.name}' claims group '${group}', which has no header`);
    const list = memberIndexes.get(group);
    if (list) list.push(i);
    else memberIndexes.set(group, [i]);
  });

  for (const [group, headerIndex] of headerAt) {
    const members = memberIndexes.get(group);
    if (!members) throw new Error(`Group '${group}' has a header but no members`);
    if (members[0] !== headerIndex + 1) {
      throw new Error(`Group '${group}' members must directly follow their header`);
    }
    if (members[members.length - 1] - members[0] !== members.length - 1) {
      throw new Error(`Group '${group}' members must be contiguous`);
    }
  }
}

/**
 * A section's own bytes, without its separator.
 *
 * The empty-`titled` case is why the join cannot simply append `\n\n` to a
 * rendered heading: `## name\n\n` plus the join's separator emits three
 * newlines, and byte-parity fails at the tail.
 */
function renderSection(s: ComposedSection): string {
  if (s.heading.kind === 'verbatim') return s.body;
  const heading = `${'#'.repeat(s.heading.level)} ${s.name}`;
  return s.body ? `${heading}\n\n${s.body}` : heading;
}

function assemble(marker: string, sections: readonly ComposedSection[]): string {
  return measure(marker, sections).content;
}

/**
 * Assemble once, and derive every per-section byte count by SLICING that result.
 *
 * Ownership: each section owns its own bytes plus the `\n\n` that follows it,
 * clipped at the trim boundary; the final section owns whatever survives the trim
 * plus the single terminal `\n`. So `sum(sections) + markerBytes + 2 === total`.
 *
 * Slicing is what makes that identity hold, and re-measuring is what broke it
 * twice. `renderSection(s).length + 2` charges the last section two newlines the
 * trim has already removed; adding `+ 1` for the final section fixes only the case
 * where that section ends in a non-space character. A section whose body ends in
 * spaces or blank lines — `'tail   \n\n'` — has those bytes trimmed too, and no
 * per-section constant can predict how many. The overcount then propagates into
 * eviction: the ladder picks the section with the largest count, so a body padded
 * with trailing whitespace can outrank a genuinely larger one and be evicted in
 * its place, dropping content that was not the problem.
 */
function measure(
  marker: string,
  sections: readonly ComposedSection[],
): { content: string; total: number; sections: { readonly name: string; readonly bytes: number }[] } {
  const rendered = sections.map(renderSection);
  const raw = [marker, ...rendered].join('\n\n');
  const kept = raw.trimEnd().length;
  const content = raw.slice(0, kept) + '\n';

  // Character offset of each section's block within `raw`, marker first.
  const starts: number[] = [];
  let at = marker.length + SEPARATOR_BYTES;
  for (const text of rendered) {
    starts.push(at);
    at += text.length + SEPARATOR_BYTES;
  }

  const counts = rendered.map((_, i) => {
    const from = Math.min(starts[i], kept);
    const to = i === rendered.length - 1 ? kept : Math.min(starts[i + 1], kept);
    // The terminal `\n` replaces everything the trim removed, so the final
    // section owns exactly one byte for it.
    const terminal = i === rendered.length - 1 ? 1 : 0;
    return {
      name: sections[i].name,
      bytes: Buffer.byteLength(raw.slice(from, to), 'utf-8') + terminal,
    };
  });

  return { content, total: Buffer.byteLength(content, 'utf-8'), sections: counts };
}

/**
 * Runtime guard for the non-empty contract. The tuple type stops a new caller
 * passing a literal `[]`, but a `JSON.parse`d or `as`-cast value reaches here
 * unchecked, and the failure it would cause (a group spawning with no
 * instructions) is silent.
 */
function requireSections(
  sections: readonly ComposedSectionInput[],
): readonly [ComposedSectionInput, ...ComposedSectionInput[]] {
  if (sections.length === 0) throw new Error('Composed document requires at least one section');
  return sections as readonly [ComposedSectionInput, ...ComposedSectionInput[]];
}

/**
 * Assemble, then evict largest-droppable-first until the document fits.
 *
 * PURE, and the staleness sweep depends on it: spawn and `detectStaleContainers`
 * both hash this output, so a decision that varied between the two calls would
 * make the digests disagree forever and respawn the container every 60s. That is
 * also why nothing here logs — the sweep calls it every 60s, and a near-cap
 * document would emit the same warning until someone fixed it. The caller logs,
 * after publication succeeds.
 */
export function renderProjectDoc(marker: string, spec: ProjectDocSpec): RenderedProjectDoc {
  const input = requireSections(spec.extraSections);
  validate(input);

  const live: ComposedSection[] = [...input];
  const dropped: string[] = [];
  const structurallyOmitted: string[] = [];
  const { maxBytes } = spec;

  // The exact list that was measured, kept alongside the measurement. `live` and
  // `current.sections` are index-aligned only while the notice is absent, so the
  // ranking below needs a way back from a live section to its measured bytes.
  let measured = withNotice(live, dropped);
  let current = measure(marker, measured);

  if (maxBytes !== undefined) {
    while (current.total > maxBytes) {
      // Ranked by the bytes this section actually contributes to the document —
      // the same slice-derived counts the diagnostics report. Re-measuring
      // `renderSection` instead ranks by bytes the trim removes, so a section
      // padded with trailing whitespace could outrank a larger one and be evicted
      // in its place.
      //
      // Aligned by OCCURRENCE, not by identity. `measured` is `live` plus at most
      // one notice, so dropping the notice's entry restores index alignment with
      // `live` exactly. Any keyed lookup assumes sections are distinguishable:
      // nothing requires names to be unique (two MCP servers, two skills), and
      // nothing requires the objects themselves to be distinct either — a producer
      // may legitimately push one object twice. Both collapse to one count, and a
      // collapsed count evicts the wrong section.
      const liveBytes = current.sections.filter((_, i) => measured[i].role !== 'notice');
      let victim = -1;
      let victimBytes = -1;
      for (let i = 0; i < live.length; i++) {
        const s = live[i];
        if (!s.droppable) continue;
        const bytes = liveBytes[i].bytes;
        if (bytes > victimBytes) {
          victim = i;
          victimBytes = bytes;
        }
      }

      if (victim === -1) {
        // Nothing left but core. Upstream's `if (!largest) break` writes the
        // oversized document, which Claude Code silently ignores in full —
        // leaving the agent with NO instructions. Refusing lets
        // `assertComposedDocUsable` keep an existing group on its previous
        // document and refuse a fresh spawn loudly.
        //
        // Diagnostics carry the notice too: after a partial eviction it is a real
        // section in the measured document, and omitting it made the reported
        // per-section bytes fail to account for the total the same error reports.
        // Sorted largest-first because the message calls them "Largest sections"
        // and only shows the top three — document order would name three small
        // ones and omit the culprit.
        throw new ProjectDocTooLargeError(
          current.total,
          maxBytes,
          [...current.sections].sort((a, b) => b.bytes - a.bytes).map((s) => ({ section: s.name, bytes: s.bytes })),
          dropped,
        );
      }

      dropped.push(live[victim].name);
      live.splice(victim, 1);
      pruneEmptyGroups(live, structurallyOmitted);
      measured = withNotice(live, dropped);
      current = measure(marker, measured);
    }
  }

  // One measurement feeds the content, the total, and the per-section counts, so
  // the sum identity holds by construction.
  const final = current;
  const content = final.content;

  return {
    content,
    hash: crypto.createHash('sha256').update(content).digest('hex'),
    dropped,
    diagnostics: {
      bytes: final.total,
      maxBytes,
      sections: [...final.sections].sort((a, b) => b.bytes - a.bytes),
      nearCap: maxBytes !== undefined && final.total >= maxBytes - maxBytes / 8,
      structurallyOmitted,
    },
  };
}

/** Drop group headers whose last member was just evicted. */
function pruneEmptyGroups(live: ComposedSection[], structurallyOmitted: string[]): void {
  for (let i = live.length - 1; i >= 0; i--) {
    const s = live[i];
    if (s.role !== 'group-header') continue;
    const hasMember = live.some((m) => m.role === 'body' && m.group === s.group);
    if (hasMember) continue;
    structurallyOmitted.push(s.name);
    live.splice(i, 1);
  }
}

/**
 * Insert the size notice immediately BEFORE the persona.
 *
 * Upstream appends it, which on this fork would place a generated notice after
 * the operator's own instructions and invert the last-word precedence stated at
 * `spine.ts:919-921`. No persona ⇒ the notice goes last.
 */
function withNotice(live: readonly ComposedSection[], dropped: readonly string[]): readonly ComposedSection[] {
  if (dropped.length === 0) return live;
  const notice: ComposedSection = {
    role: 'notice',
    droppable: false,
    name: 'Omitted for size',
    heading: { kind: 'titled', level: 2 },
    body: `These sections were omitted to keep this document under its size cap: ${dropped.join(', ')}.`,
  };
  const personaIndex = live.findIndex((s) => s.role === 'persona');
  if (personaIndex === -1) return [...live, notice];
  return [...live.slice(0, personaIndex), notice, ...live.slice(personaIndex)];
}

export { PROJECT_DOC_MAX_BYTES };
